/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    ArtistListByType: typeof import('./components/ArtistListByType.vue')['default']
    CoverImage: typeof import('./components/CoverImage.vue')['default']
    Dropdown: typeof import('./components/common/Dropdown.vue')['default']
    IconNcm: typeof import('./components/icon/IconNcm.vue')['default']
    IconQQ: typeof import('./components/icon/IconQQ.vue')['default']
    LucideChevronDown: typeof import('lucide-vue-next')['ChevronDown']
    LucideChevronLeft: typeof import('lucide-vue-next')['ChevronLeft']
    LucideGripVertical: typeof import('lucide-vue-next')['GripVertical']
    LucideLayoutGrid: typeof import('lucide-vue-next')['LayoutGrid']
    LucideList: typeof import('lucide-vue-next')['List']
    LucideListEnd: typeof import('lucide-vue-next')['ListEnd']
    LucideLoader2: typeof import('lucide-vue-next')['Loader2']
    LucidePause: typeof import('lucide-vue-next')['Pause']
    LucidePlay: typeof import('lucide-vue-next')['Play']
    LucidePlus: typeof import('lucide-vue-next')['Plus']
    LucideRepeat: typeof import('lucide-vue-next')['Repeat']
    LucideRepeat1: typeof import('lucide-vue-next')['Repeat1']
    LucideShuffle: typeof import('lucide-vue-next')['Shuffle']
    LucideSkipBack: typeof import('lucide-vue-next')['SkipBack']
    LucideSkipForward: typeof import('lucide-vue-next')['SkipForward']
    LucideSlidersHorizontal: typeof import('lucide-vue-next')['SlidersHorizontal']
    LucideVolume2: typeof import('lucide-vue-next')['Volume2']
    LucideVolumeX: typeof import('lucide-vue-next')['VolumeX']
    LucideX: typeof import('lucide-vue-next')['X']
    OverlayScrollbarsComponent: typeof import('overlayscrollbars-vue')['OverlayScrollbarsComponent']
    PlayerBar: typeof import('./components/player/PlayerBar.vue')['default']
    PlayerFullscreen: typeof import('./components/player/PlayerFullscreen.vue')['default']
    PlayerLyrics: typeof import('./components/player/PlayerLyrics.vue')['default']
    PlayerPlaylist: typeof import('./components/player/PlayerPlaylist.vue')['default']
    PlayerProgress: typeof import('./components/player/PlayerProgress.vue')['default']
    PlayerSpectrum: typeof import('./components/player/PlayerSpectrum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./components/common/Tooltip.vue')['default']
  }
}
