/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    ArtistListByType: typeof import('./components/ArtistListByType.vue')['default']
    BackgroundLayer: typeof import('./components/BackgroundLayer.vue')['default']
    CoverImage: typeof import('./components/CoverImage.vue')['default']
    Dropdown: typeof import('./components/common/Dropdown.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconNcm: typeof import('./components/icon/IconNcm.vue')['default']
    IconQQ: typeof import('./components/icon/IconQQ.vue')['default']
    LucideAudioLines: typeof import('@lucide/vue')['AudioLines']
    LucideChevronDown: typeof import('@lucide/vue')['ChevronDown']
    LucideChevronLeft: typeof import('@lucide/vue')['ChevronLeft']
    LucideGripVertical: typeof import('@lucide/vue')['GripVertical']
    LucideLayoutGrid: typeof import('@lucide/vue')['LayoutGrid']
    LucideList: typeof import('@lucide/vue')['List']
    LucideListEnd: typeof import('@lucide/vue')['ListEnd']
    LucideLoader2: typeof import('@lucide/vue')['Loader2']
    LucidePause: typeof import('@lucide/vue')['Pause']
    LucidePlay: typeof import('@lucide/vue')['Play']
    LucidePlus: typeof import('@lucide/vue')['Plus']
    LucideRepeat: typeof import('@lucide/vue')['Repeat']
    LucideRepeat1: typeof import('@lucide/vue')['Repeat1']
    LucideSearch: typeof import('@lucide/vue')['Search']
    LucideShuffle: typeof import('@lucide/vue')['Shuffle']
    LucideSkipBack: typeof import('@lucide/vue')['SkipBack']
    LucideSkipForward: typeof import('@lucide/vue')['SkipForward']
    LucideSlidersHorizontal: typeof import('@lucide/vue')['SlidersHorizontal']
    LucideUser: typeof import('@lucide/vue')['User']
    LucideVolume2: typeof import('@lucide/vue')['Volume2']
    LucideVolumeX: typeof import('@lucide/vue')['VolumeX']
    LucideX: typeof import('@lucide/vue')['X']
    OverlayScrollbarsComponent: typeof import('overlayscrollbars-vue')['OverlayScrollbarsComponent']
    PlayerBar: typeof import('./components/player/PlayerBar.vue')['default']
    PlayerFullscreen: typeof import('./components/player/PlayerFullscreen.vue')['default']
    PlayerLyrics: typeof import('./components/player/PlayerLyrics.vue')['default']
    PlayerPlaylist: typeof import('./components/player/PlayerPlaylist.vue')['default']
    PlayerProgress: typeof import('./components/player/PlayerProgress.vue')['default']
    PlayerSpectrum: typeof import('./components/player/PlayerSpectrum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./components/SearchModal.vue')['default']
    TagList: typeof import('./components/TagList.vue')['default']
    Tooltip: typeof import('./components/common/Tooltip.vue')['default']
  }
}
