/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    ArtistListByType: typeof import('./components/ArtistListByType.vue')['default']
    Dropdown: typeof import('./components/common/Dropdown.vue')['default']
    IconNcm: typeof import('./components/icon/IconNcm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
  }
}
